#!/usr/bin/env node
const commander = require('commander');

const action = (args) => {
  console.log('args', args);
  // parse config from provided file

}

const cli = new commander.Command();
cli
    .option('-l, --list', 'list all options')
    .option('-d, --dry', 'do a dry-run without installing anything')
    .description('sets up your workstation to get you ready to build')
    .action(action);

cli.parse(process.argv);
